runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /fonts
  static_dir: static/fonts

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /api/.*
  script: api.app

- url: /tasks/.*
  script: tasks.app
  login: admin

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest




